/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectopatrones.interfaz;

import proyectopatrones.clases.Administrador;
import proyectopatrones.interfaz.FormularioCasos;
import java.sql.DriverManager;
import java.sql.Connection;
import java.lang.ClassNotFoundException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class AdminInterface extends javax.swing.JFrame {
    private Statement stmt;
    private ResultSet res;
    private String[] fila;
    private DefaultTableModel model;
    private FormularioCasos formulario_casos;
    private FormularioCierre formulario_cierre;
    private FormularioInvestigador formulario_investigador;
    private FormularioSeguimiento formulario_seguimiento;
    private Administrador admin;
    /**
     * Creates new form AdminInterface
     */
    public AdminInterface(){
        initComponents();
        admin = new Administrador();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           admin.con = DriverManager.getConnection("jdbc:mysql://localhost/CasosInv", "root", "");
           formulario_casos = new FormularioCasos(admin, 1);
           
           /**** avisamos ****/
           //System.out.println( "Si he llegado hasta aquí es que se ha producido la conexión");
           //System.out.println( "Si no se hubiera producido, se habría disparado SQLException");
           
           fila = new String[4];
           stmt = admin.con.createStatement();
           RefreshCartelera();
        }
       /**** Excepción que se dispara si falla la carga del driver ****/
        catch( ClassNotFoundException e ) { e.printStackTrace();  }

       /**** Excepción que se dispara si falla la conexión *****/
        catch ( SQLException e) { e.printStackTrace();  }
        
    }
    
    public void RefreshCartelera(){
        try{
            res = stmt.executeQuery("select nro_expediente, tipo_de_caso, investigador, estado from casos_de_investigacion");
            String titulos[] = {"Nro Expediente", "Tipo de Caso", "Investigador", "Estado"};
            model = new DefaultTableModel(null, titulos);
            while (res.next()){
               //System.out.println(res.getString(1) + " " + res.getString(2) + " " + res.getString(3) + " " + res.getString(4));
               fila[0] = res.getString(1);
               fila[1] = res.getString(2);
               fila[2] = res.getString(3);
               fila[3] = res.getString(4);
               
               model.addRow(fila);
            }
            cartelera.setModel(model);
        }
        catch ( SQLException e) { e.printStackTrace();  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartelera = new javax.swing.JTable();
        admin_title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        crear = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        cerrar = new javax.swing.JMenuItem();
        marcar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        asignar = new javax.swing.JMenuItem();
        seguimiento = new javax.swing.JMenuItem();
        entidades = new javax.swing.JMenuItem();
        reporte = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        amonestados = new javax.swing.JMenuItem();
        robos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro Expediente", "Tipo de Caso", "Investigador", "Estado"
            }
        ));
        jScrollPane1.setViewportView(cartelera);
        cartelera.getColumnModel().getColumn(0).setHeaderValue("Nro Expediente");
        cartelera.getColumnModel().getColumn(1).setHeaderValue("Tipo de Caso");
        cartelera.getColumnModel().getColumn(2).setHeaderValue("Investigador");
        cartelera.getColumnModel().getColumn(3).setHeaderValue("Estado");

        admin_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        admin_title.setText("Bienvenido <Administrador>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Casos de investigación ");

        refresh.setText("Refrescar");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(admin_title, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(247, 247, 247))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(admin_title, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(refresh)
                .addGap(21, 21, 21))
        );

        jMenu1.setText("Archivo");

        crear.setText("Crear caso");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jMenu1.add(crear);

        abrir.setText("Abrir caso");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jMenu1.add(abrir);

        cerrar.setText("Cerrar caso");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jMenu1.add(cerrar);

        marcar.setText("Marcar caso");
        marcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcarActionPerformed(evt);
            }
        });
        jMenu1.add(marcar);
        jMenu1.add(jSeparator1);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acción");

        asignar.setText("Asignar investigador");
        asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarActionPerformed(evt);
            }
        });
        jMenu2.add(asignar);

        seguimiento.setText("Realizar seguimiento");
        seguimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguimientoActionPerformed(evt);
            }
        });
        jMenu2.add(seguimiento);

        entidades.setText("Gestionar entidades");
        jMenu2.add(entidades);

        reporte.setText("Emitir reporte");
        jMenu2.add(reporte);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Manejar");

        amonestados.setText("Personal amonestado");
        jMenu3.add(amonestados);

        robos.setText("Equipos robados");
        robos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robosActionPerformed(evt);
            }
        });
        jMenu3.add(robos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
       formulario_casos.setVisible(true);
    }//GEN-LAST:event_crearActionPerformed

    private void marcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarActionPerformed
        int fila = cartelera.getSelectedRow();
        String nro_exp = (String) cartelera.getValueAt(fila,0);     
        admin.MarcarArchivo(nro_exp);
    }//GEN-LAST:event_marcarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        int fila = cartelera.getSelectedRow();
        String nro_exp = (String) cartelera.getValueAt(fila,0);     
        admin.AbrirCaso(nro_exp);
    }//GEN-LAST:event_abrirActionPerformed

    private void seguimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguimientoActionPerformed
        int fila = cartelera.getSelectedRow();
        String nro_exp = (String) cartelera.getValueAt(fila,0);
        String tipo_caso = (String) cartelera.getValueAt(fila,1);
        if(tipo_caso.equals("Fraude")){
            formulario_seguimiento = new FormularioSeguimiento(admin, nro_exp);
            formulario_seguimiento.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error: el caso seleccionado tiene que ser de tipo Fraude");
        }
    }//GEN-LAST:event_seguimientoActionPerformed

    private void robosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_robosActionPerformed

    private void asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarActionPerformed
        int fila = cartelera.getSelectedRow();
        String nro_exp = (String) cartelera.getValueAt(fila,0);
        formulario_investigador = new FormularioInvestigador(admin, nro_exp);
        formulario_investigador.setVisible(true);
    }//GEN-LAST:event_asignarActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        RefreshCartelera();
    }//GEN-LAST:event_refreshActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        int fila = cartelera.getSelectedRow();
        String nro_exp = (String) cartelera.getValueAt(fila,0);
        String state = (String) cartelera.getValueAt(fila,3);
        if(!state.equals("Cerrado")){
            formulario_cierre = new FormularioCierre(admin, nro_exp);
            formulario_cierre.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error: el caso se encuentra cerrado");
        }
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JLabel admin_title;
    private javax.swing.JMenuItem amonestados;
    private javax.swing.JMenuItem asignar;
    private javax.swing.JTable cartelera;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JMenuItem crear;
    private javax.swing.JMenuItem entidades;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem marcar;
    private javax.swing.JButton refresh;
    private javax.swing.JMenuItem reporte;
    private javax.swing.JMenuItem robos;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem seguimiento;
    // End of variables declaration//GEN-END:variables
}
